---
title: "clean clean clean <3"
author: "Naomi Liftman"
date: "2/23/2022"
output: pdf_document
---
# Load Files
```{r}
#load all necessary packages
library(tidyverse)
library(psych)
```

# Import Premeasures and Clean
```{r}
#import the data
pre <- read_csv("TeleCom_Dyad_premeasures.csv")

#clean the data so it is numeric
pre <- pre %>%
  mutate(asi_1 = as.numeric(gsub("[a-zA-Z]", "", asi_1)),
         asi_2 = as.numeric(gsub("[a-zA-Z]", "", asi_2)),
         asi_3 = as.numeric(gsub("[a-zA-Z]", "", asi_3)),
         asi_4 = as.numeric(gsub("[a-zA-Z]", "", asi_4)),
         asi_5 = as.numeric(gsub("[a-zA-Z]", "", asi_5)),
         asi_6 = as.numeric(gsub("[a-zA-Z]", "", asi_6)),
         asi_7 = as.numeric(gsub("[a-zA-Z]", "", asi_7)),
         asi_8 = as.numeric(gsub("[a-zA-Z]", "", asi_8)),
         asi_9 = as.numeric(gsub("[a-zA-Z]", "", asi_9)),
         asi_10 = as.numeric(gsub("[a-zA-Z]", "", asi_10)),
         asi_11 = as.numeric(gsub("[a-zA-Z]", "", asi_11)),
         asi_12 = as.numeric(gsub("[a-zA-Z]", "", asi_12)),
         asi_13 = as.numeric(gsub("[a-zA-Z]", "", asi_13)),
         asi_14 = as.numeric(gsub("[a-zA-Z]", "", asi_15)),
         asi_15 = as.numeric(gsub("[a-zA-Z]", "", asi_15)),
         asi_16 = as.numeric(gsub("[a-zA-Z]", "", asi_16)),
         asi_17 = as.numeric(gsub("[a-zA-Z]", "", asi_17)),
         asi_18 = as.numeric(gsub("[a-zA-Z]", "", asi_18)),
         asi_19 = as.numeric(gsub("[a-zA-Z]", "", asi_19)),
         asi_20 = as.numeric(gsub("[a-zA-Z]", "", asi_20)),
         asi_21 = as.numeric(gsub("[a-zA-Z]", "", asi_21)),
         asi_22 = as.numeric(gsub("[a-zA-Z]", "", asi_22)))

#reversing all the variables that need it 
pre <- pre %>% 
  mutate(asi_3.r = (1+6) - asi_3,
         asi_6.r = (1+6) - asi_6,
         asi_7.r = (1+6) - asi_7,
         asi_13.r = (1+6) - asi_13,
         asi_18.r = (1+6) - asi_18,
         asi_21.r = (1+6) - asi_21)
```

# Look at benevolent
```{r}
#pull out for benevolent sexism
benevbaby <- pre %>% 
  select(dyadID, asi_1, asi_3.r, asi_6.r, asi_8, asi_9, asi_12, asi_13.r, asi_17, asi_19, asi_20, asi_22)

#benevolent correlation matrix
corr.test(select(benevbaby, asi_1:asi_22))$r
```

# Look at hostile
```{r}
#pull out for hostile sexism
hostilebaby <- pre %>% 
  select(dyadID, asi_2, asi_4, asi_5, asi_7.r, asi_10, asi_11, asi_14, asi_15, asi_16, asi_18.r, asi_21.r)

#hostile correlation matrix
corr.test(select(hostilebaby, asi_2:asi_21.r))$r
#question 18 is still giving us problems :(, where in the actual qualtrics survey
#the question should be reversed but maybe ppl just didnt understand the question
#should we get rid of the question? idk
```

# Calculate reliability
```{r}
#reliability for the benevolent
alpha(select(benevbaby, asi_1:asi_22))
#raw alpha is 0.8001697

#reliability for the hostile
alpha(select(hostilebaby, asi_2:asi_21.r))
#raw alpha is 0.8549932
```

# Actually Creating Scale Scores
```{r}
#the alpha for both of our variables is above .7, so we are swag
#now we are going to merge the new datasets back together
pre_fixed <- benevbaby %>% 
  inner_join(hostilebaby, by = "dyadID")

#benevolent own variable
pre_fixed$benevolaet <- rowMeans(select(pre_fixed, asi_1, asi_3.r, asi_6.r, asi_8, asi_9, asi_12, asi_13.r, asi_17, asi_19, asi_20, asi_22))

#hostile own variable
pre_fixed$hostile <- rowMeans(select(pre_fixed, asi_2, asi_4, asi_5, asi_7.r, asi_10, asi_11, asi_14, asi_15, asi_16, asi_18.r, asi_21.r))
```

# Daily
```{r}
daily <- read_csv("TeleCom_Dyad_dailydiary.csv")

#cleaning data to only include our sample size and the variables we are measuring
daily <- daily %>%
  select(dyadID, RecordedDate, gender, beds:calls, qmi4) 

sexor <- read_csv("TeleCom_Dyad_premeasures.csv") %>%
  select(dyadID, sexualor)
  
chores <- daily %>%
  left_join(sexor, by = "dyadID") %>%
  filter(sexualor == "Heterosexual")

# Making chore data numeric
chores <- chores %>%
  mutate(beds = if_else(beds == "Yes", 1, 0),
         vacuum = if_else(vaccum == "Yes", 1, 0),
         food = if_else(food == "Yes", 1, 0),
         dishes = if_else(dishes == "Yes", 1, 0),
         garbage = if_else(garbage == "Yes", 1, 0),
         yardwork = if_else(yardwork == "Yes", 1, 0),
         pets = if_else(pets == "Yes", 1, 0),
         laundry = if_else(laundry == "Yes", 1, 0),
         errands = if_else(errands == "Yes", 1, 0),
         cars = if_else(cars == "Yes", 1, 0),
         finances = if_else(finances == "Yes", 1, 0),
         events = if_else(events == "Yes", 1, 0),
         calls = if_else(calls == "Yes", 1, 0)) %>%
  select(-vaccum, sexualor) %>%
  distinct()

chores[, 4:15][is.na(chores[, 4:15])] <- 0

chores <- chores %>%
  rowwise() %>%
  mutate(ind_chores = sum(beds, food, dishes, garbage, yardwork, pets, laundry, errands, cars, finances, events, calls, vacuum))
```
