---
title             : "Introduction"
shorttitle        : "Introduction"

author: 
  - name          : "Naomi Liftman"
    affiliation   : "1" 
  - name          : "Cara Krupnikoff-Salkin"
    affiliation   : "1"
   
affiliation:
  - id            : "1"
    institution   : "Smith College"

bibliography      : ["psy-references-intro.bib", "r-references-intro.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_word
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references-intro.bib")
```

For many decades, women in dual-earner households were found to do a significant portion of the housework [@Bareket], thus creating a so-called “second shift” of work for women when they returned home. In May of 2020, as the devastation of the COVID-19 pandemic began to set in, nearly 48% of the Americans that had previously commuted to work in February were either working from home or unemployed [@Bick]. As a result of the pandemic, the entire American workforce was rearranged, leading to a dual purpose of the current study. The first is to synthesize previous research findings on the relationship between sexism, marital satisfaction, and the division of housework in the context of romantic relationships, while determining whether these findings hold true during such unprecedented times. The second is to explore these concepts through a dyadic lens, by looking at the experiences of both partners within a heterosexual relationship. 

## Sexism in Romantic Couples

When looking at the mechanisms that play into the differences within and between heterosexual couples, it is important to acknowledge the different forms of sexism that occur. Under the theory of ambivalent sexism, there are two forms of sexism.  There is hostile sexism (HS): where women are treated with resent, and often aggression. And there is benevolent sexism (BS): where women are cared for, but seen as helpless and incompetent [@Glick1996]. Furthermore, BS and HS interact to create the structure of gender inequality that is present within our modern-day society. While HS punishes women for breaking traditional gender roles, BS rewards them for taking on traditionally feminine roles [@Glick2001]. As a result, ambivalent sexism has a strong influence on interpersonal relationships. Within a romantic couple, men who are higher in BS tend to seek women who fulfill more traditional gender roles [@Thomae]. Moreover, men who are high in HS seek women who are high in BS, and vice versa [@Lee]. Individuals who are higher in either form of sexism are more likely to have partnerships that fit more traditional gender prescriptions. 

Additionally, @Hammond found that women who were high in BS experienced very high relationship satisfaction if their benevolent ideals were met, but very low satisfaction if they weren’t. Conversely, they found that a man's relationship satisfaction had more to do with his overall status (inside and outside the home) than on his partner’s fulfillment of her gender role. @Minnotte shows that the relationship between gender ideologies and marital satisfaction is complex. In their study, when husbands were lower in sexism and the household was more egalitarian, husbands reported less relationship satisfaction. This indicates that in addition to behaviors and reported beliefs, there are unseen factors that influence gender bias. @Lee also found that even when Americans don’t directly endorse BS attitudes, they are still likely to be guided by BS when choosing their partners, highlighting how even in instances where people don’t present bias outwardly, they are often still influenced by gender ideologies.

## Dividing Housework

	A prominent manner of observing bias from gender ideologies is through the division of household labor. Typically, women do more frequent, routine chores, such as cleaning, and men do more occasional, intermittent chores, such as car maintenance [@Barstad]. This leads to a misalignment, where even with increasing gender equality within the workforce, women are doing disproportionately more work [@Helms]. It is important to note that calculations of housework are often biased. Stereotypical men and women engage in different types of chores, so any calculation based on a set list of chores may miss the larger picture of how the couple chooses to divide their work on any given day [@Nordenmark]. Regardless, focusing specifically on only traditionally feminine tasks allows us to highlight the gender mismatch in the proportion of everyday tasks taken on by different members of a household.

While dual-earning heterosexual households may have *more* egalitarian divisions of housework [@Chesters], the divisions are still uneven. In fact, @Barstad found that in the cases in which there is greater equality in the division of household labor, it is because the women have decreased their housework, as opposed to the men taking on more. This leads to an inequity  where women and men have different concepts of what equal division of housework may mean. Additionally, division of housework is influenced heavily by the individual partners’ work environments, especially when the partners are not dual earners. When husbands  work or earn more than their wives, wives end up taking on a larger proportion of the housework [@Lam]. Similarly, when husbands are dealing with stress from work that extends back to their home, the wife is more likely to take on more work [@Lam; @Huffman].  This last finding is particularly relevant to the context of the COVID-19 pandemic, in which many couples have been forced to work from home. In order to gain insight into the process through which chores are divided, it is important to determine how couples are responding to changes in status and the spillover of work-family conflict during these unprecedented times.

## Sexism and Marital Satisfaction Linked with Division of Housework

Many of the factors that influence the ways in which housework is divided are linked closely with sexism. In general, when couples exhibit more traditional gender ideologies, the woman is likely to do more housework [@Erickson]. When one partner exhibits different sexist beliefs than the other, the division of household labor continues to be uneven [@Bareket]. In studying attitudes toward provider roles, @Helms found that those who endorse the main-secondary provider and ambivalent coprovider attitudes — those that relate most closely to BS beliefs [@Carlson] — the wife is more likely to do the majority of the housework. @Doan found that it is much more common and acceptable for the wife to take on masculine tasks in addition to feminine (routine) ones than it is for the husband to take on any of the feminine tasks. This leads to an imbalance in which women are often left doing more than men. At the same time, according to @Poortman, one of the main underlying causes of unequal division of household labor is because women prefer to do the routine house chores. In many cases, the wife’s prescriptions guide her to take on a traditional role within the household. Additionally, although the husband has traditionally had a more dominant role in determining the gender roles within the relationship [@Lam; @Huffman], the wife also has a strong influence on whether the division of housework will be more traditional or not. When the wife endorses more traditional gender ideologies, even if the husband doesn’t, the wife is likely to do more housework [@Greenstein1996]. When the wife does not endorse BS, it is more likely for there to be an equal division of housework [@Helms]. While many studies have looked individually at the effect that the husband’s and the wife’s sexist attitudes have on their division of household labor, less has looked at *how* the relationship between their gender ideologies may have an impact.

There is also a strong link between division of household labor and feelings of marital satisfaction. Feelings of fairness and equality within the partnership are more strongly linked to the distribution of housework than to the division of paid work [@Nordenmark]. In countries with  higher push gender-equity, such as America, the distribution of household chores has a considerable effect on feelings of fairness [@Greenstein2009]. Interestingly, there are also strong relationships between the division of household labor and relationship quality in women. Women feel low levels of satisfaction when men do little to no routine housework, but women also don’t enjoy doing intermittent (masculine) tasks [@Barstad]. Coupled with gender ideologies, division of household labor has a strong impact on feelings of marital satisfaction. When the wife takes on less of a traditional role and participates more in the workforce, she is less likely to be satisfied with doing more housework [@Braun]. Similarly, people who endorse different sexist beliefs are likely to have different perceptions about what divisions of housework are equitable, influencing feelings about fairness, teamwork, and marital quality [@Bareket; @Nordenmark]. It is rare for two partners to share the exact same gender ideologies, and gender ideologies have an impact on the division of housework and on overall marital satisfaction. Each individual person’s beliefs have an impact on their own feelings, but also on their partner’s, making it important to investigate these variables from a dyadic perspective.

## Current Study

Previous research shows that there are links between sexism and division of household labor, sexism and marital satisfaction, and division of household labor and marital satisfaction. While some research looks at the relationship between all three of these variables, it fails to address the relationship that the two partners have with each other. In this study, we attempted to gain a more holistic understanding of how the interaction between partners influences their individual attitudes towards sexism, feelings about the quality of the relationship, and the percentage of housework that they are a part of. Couples were asked about their feelings about their relationship and the household chores that they did for two weeks, with the goals of (1) determining the extent to which the husbands’ and the wives’ attitudes of sexism impacted their own and each other’s feelings of marital satisfaction, and (2) the extent to which division of labor may have acted as a moderator between the two variables. We approached the data dyadically, using the Actor-Partner Interdependence Model [APIM; @Kenny]. This allowed us to operate under the assumption that the romantic partners are not independent from each other, and to investigate the effects both the respondents (actors) and their partners (partners) had on each other.

	Our first hypothesis was that individuals who were higher in sexism would have higher feelings of marital satisfaction if their partners were also higher in sexism. Given the findings by @Thomae and @Lee, we hypothesized that this would be especially true for scenarios in which women were high in BS and men were high in either HS or BS (Hypothesis 1a). Our second hypothesis was that the relationship between sexism and marital quality would be moderated by the division of household labor. More specifically, we predicted that when both partners were higher in sexism, and the division of housework would be more traditional, with the woman doing more routine housework causing both partners to have greater feelings of satisfaction (Hypothesis 2a). In instances where one partner was higher in sexism than the other, we predicted that the division of housework would be traditional, and that the man would be more satisfied (Hypothesis 2b); if the woman was high in sexism, she would be as satisfied or more satisfied than the man (Hypothesis 2c); if she was low in sexism, she would be less satisfied than the man (Hypothesis 2d). Lastly, if both partners were low in sexism and the division of housework was more egalitarian, both partners would be satisfied (Hypothesis 2e). While each of these hypotheses was drawn from empirical literature that described the relationship of these components on an individual level, we anticipated that there may be contradictory findings once we take into account the potential dyadic interaction within each couple for these variables. 


